const LOG_EVENTS = {
  CREATE_AUDIO: "create_audio",
  CREATE_COMMENT: "comment",
  CREATE_WIP: "create_wip",
  DELETE_AUDIO: "delete_audio",
  DELETE_WIP: "delete_wip",
  DOWNLOAD_AUDIO: "download_audio",
  INVALID_FILE: "invalid_file",
  LOGIN: "login",
  NOTES: "notes",
  OPEN_AUDIO: "open_audio",
  OPEN_DESKTOP_TAB: "open_desktop_tab",
  OPEN_FOLDER: "open_folder",
  OPEN_NOTIFICATIONS: "open_notifications",
  OPEN_WIP: "open_wip",
  PAUSE_BUTTON: "pause_button",
  PLAY_BUTTON: "play_button",
  PROFILE: "profile",
  RECORD: "record",
  SHARE_AUDIO: "share_audio",
  TAP_ACTIVITY: "tap_activity",
  VIEW_ACCOUNT: "view_account",
  // SHARE_WIP: "share_wip",
};

export default LOG_EVENTS;
