export const removeSymbols = (string) =>
  string
    .replace(/!/, '')
    .replace(/#/, '')
    .replace(/\?/, '')
    .replace(/'/, '')
    .replace(/%/, '')
    .replace(/,/, '')
    .replace(/\*/, '')
    .replace(/\$/, '')
    .replace(/\(/, '')
    .replace(/\)/, '')
    .replace(/"/, '')
    .replace(/ /, '')
    .replace(/&/, '')
    .replace(/\+/, '')
    .replace(/\-/, '')
    .replace(/\./, '')
    .replace(/;/, '')
    .replace(/:/, '')
    .replace(/=/, '')
    .replace(/@/, '')
    .replace(/</, '')
    .replace(/>/, '')
    .replace(/[0-9]/, '');
